name: preab_message
description: A chat module with Firebase.
version: 0.0.1
homepage:

publish_to: "none"

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  future_manager: ^1.3.0
  #firebase
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  firebase_storage: ^10.3.11
  timeago: ^3.3.0
  skadi_firebase:
    git:
      url: https://github.com/lynical-software/skadi_firebase
      ref: v0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
