name: preab_message
description: A chat module with Firebase.
version: 1.4.0
homepage:

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  future_manager: ^1.7.0
  #firebase
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  timeago: ^3.3.0
  skadi_firebase:
    git:
      url: https://github.com/lynical-software/skadi_firebase
      ref: v1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
