name: preab_message
description: A chat module with Firebase.
version: 1.5.0
homepage:

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  future_manager: ^1.10.0
  #firebase
  firebase_auth: 4.12.1
  cloud_firestore: 4.12.2
  firebase_storage: 11.4.1
  timeago: ^3.3.0
  skadi_firebase:
    git:
      url: https://github.com/lynical-software/skadi_firebase
      ref: v1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
